name: Create Patch Release

on:
  workflow_dispatch:

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: github-app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          token: ${{ steps.github-app-token.outputs.token }}
          ref: ${{ github.head_ref }}

      - name: Bump version
        run: |
          git config --global --add safe.directory /harness
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          ./tools/create_release.sh patch
        env:
          GITHUB_TOKEN: ${{ steps.github-app-token.outputs.token }}
